# Generated by Django 3.1.2 on 2020-10-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator', to='accounts.userprofile')),
                ('recipent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipent', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_sent', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('coversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='conversations.conversation')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='accounts.userprofile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='accounts.userprofile')),
            ],
        ),
    ]
