# Generated by Django 3.1.2 on 2020-10-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20201021_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_datetime', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.TextField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='threads.thread')),
            ],
        ),
    ]
