# Generated by Django 3.1.2 on 2020-10-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('threads', '0005_auto_20201021_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='threadcomment',
            name='poster_id',
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to='accounts.userprofile'),
        ),
    ]
