# Generated by Django 3.1.2 on 2020-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20201021_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
