# Generated by Django 3.1.2 on 2020-10-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_auto_20201025_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_type',
        ),
    ]
